### ISSUE TITLE
Tournament Wrong Play Format

### ISSUE THREAD

**Issue by uberidiot** [Badaro/MTGODecklistCache#30]
Hello,

It seems that this tournament: https://github.com/Badaro/MTGODecklistCache/blob/master/Tournaments/mtgmelee.com/2022/11/27/nrg-series-5k-trial-chicagoland-pioneer-2022-11-27.json

was posted on MtgMelee as Pioneer by mistake and later corrected. The decklists are clearly Modern.

**Comment by Badaro** [comment]
Good catch. Fixed.
