### ISSUE TITLE
Validation Errors 2023-10-26

### ISSUE THREAD

**Issue by ghost** [Badaro/MTGODecklistCache#44]
- [x] Invalid Card "Magnifying Glass Enthusiast" in 17 tournament(s) including crokeyz-crimson-vow-tournament-standard-8248-2021-11-13
- [x] Invalid Card "Voltaic Visionary" in 13 tournament(s) including crokeyz-crimson-vow-tournament-standard-8248-2021-11-13
- [x] Invalid Card A-Faceless Haven in 1 tournament(s) including new-capenna-championship-historic-seat-1-10016-2022-05-20
- [x] Invalid Card A-Hullbreaker Horror in 2 tournament(s) including midweek-tournament-black-pearl-6-no-black-color-standard-12166-2022-09-29
- [x] Invalid Card Goblin in 1 tournament(s) including radioatog-vol3-team-trio-pauper-seat-1-17900-2023-09-30
- [x] Invalid Card Name Sticker Goblin in 26 tournament(s) including legacy-preliminary-2023-09-2212582244

**Comment by Badaro** [comment]
Validation fixes implemented, pending redownload of tournaments.
