### ISSUE TITLE
Mtgo tournament updates

### ISSUE THREAD

**Issue by Never28** [Badaro/MTGODecklistCache#47]
Since Wotc retroactively changed the frequency and how results are published, do you plan to update the tournament folder with the new results starting from 2018 (latest year available on their site, haven't tried yet if we can go further back with the API)?

**Comment by Badaro** [comment]
> do you plan to update the tournament folder with the new results starting from 2018

Yes. Actually, from Nov/2015 onwards, since that's how far the mtgo.com site goes.

It's a slow process but I expect it to be finished in a few more days.

**Comment by Badaro** [comment]
Progress being tracked here:
https://github.com/Badaro/MTGODecklistCache.Tools/issues/3
