### ISSUE TITLE
Adding a field "Format"

### ISSUE THREAD

**Issue by Roofne** [Badaro/MTGODecklistCache#8]
Lorsque plusieurs format possède un même archétype, les decks sont comptés indépendament du dossier d'archétype passé en paramètre (aka format=)
ex : Tron existe en Pauper / Modern / Legacy mais je ne veux les deck que de l'un d'entre eux

- [ ] récupéré l'info du format à partir de l'url / texte html 
- [ ] ajouter un champ format dans les fichiers json de ./Tournaments
- [ ] prendre en compte le format sélectionné lors de la détection

**Comment by ghost** [comment]
Sorry, I don't speak french. :) From what I undestood from Google Translation this is about querying data for "archetype=Tron" and restricting to a single format, correct? 

In this case, what happens is that you should be using **both** format=X and filter=X when making queries. Let's say you want to find "Modern Tron decks in the last month", you should use:

`MTGOArchetypeParser.App.exe console detect format=Modern filter=Modern archetype=Tron filter=2022-11`

Also, for questions/fixes related to the tool, please use this repository, this one is just the raw data from the websites.
https://github.com/Badaro/MTGOArchetypeParser
